config/routes.rb
Nobacco::Application.routes.draw do

  devise_for :users
  resources :additional_images
  resources :checkouts
  resources :in_carts
  resources :products
  resources :sub_categories
  resources :categories
  get "carts/index"
  get "home/index"
  get "control_panel" , to: 'home#control_panel' , as: 'control_panel'
  get "contact_us" , to: 'home#contact_us' , as: 'contact'
  get "cart" , to: 'home#cart' , as: 'user_cart'
  root 'home#index'

end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
  has_one :cart  
  validates :cart_id , presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :city , :name , :adress , presence: true
  validates :telephone , length: { minimum: 10}
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :set_checkout, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @checkouts = Checkout.all
    return is_authorized
    respond_with(@checkouts)
  end

  def show
    return is_authorized
    respond_with(@checkout)
  end

  def new
    @checkout = Checkout.new
    respond_with(@checkout)
  end

  def edit
  end

  def create
    @checkout = Checkout.new(checkout_params)
    @checkout.save
    respond_to do |format|
      format.html {redirect_to root_path}
    end
  end

  def update
    @checkout.update(checkout_params)
    respond_with(@checkout)
  end

  def destroy
    @checkout.destroy
    respond_with(@checkout)
  end

  private
    def set_checkout
      @checkout = Checkout.find(params[:id])
    end

    def checkout_params
      params.require(:checkout).permit(:cart_id, :name, :telephone, :adress, :city, :email, :delivery_type , :info)
    end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/_form.html.erb
<style>
.btn-radio {
  width: 100%;
}
.img-radio {
  opacity: 0.5;
  margin-bottom: 5px;
}

.space-20 {
    margin-top: 20px;
}
</style>
<script>
$(function () {
    $('.btn-radio').click(function(e) {
        $('.btn-radio').not(this).removeClass('active')
        .siblings('input').prop('checked',false)
            .siblings('.img-radio').css('opacity','0.5');
      $(this).addClass('active')
            .siblings('input').prop('checked',true)
        .siblings('.img-radio').css('opacity','1');
    });
});
</script>
<div class="col-md-5 center-block" style="float:none;">
  <div class="panel panel-default">
    <div class="panel-body" style="">
<%= bootstrap_form_for(@checkout) do |f| %>
  <% if @checkout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkout.errors.count, "error") %> prohibited this checkout from being saved:</h2>

      <ul>
      <% @checkout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name , "Имена*" %><br>
    <%= f.text_field :name ,  hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :telephone , 'Телефон*' %><br>
    <%= f.text_field :telephone ,  hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :adress , 'Адрес*' %><br>
    <%= f.text_field :adress ,  hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :city, 'Град*' %><br>
    <%= f.text_field :city ,  hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :email , 'Email' %><br>
    <%= f.text_field :email ,  hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :info , 'Забележки' %><br>
    <%= f.text_area :info , hide_label: true , :rows => 7 %>
  </div>
  <div class="actions">
    <small>Прегледайте внимателно данните си преди да продължите.</small>
    <%= f.submit 'Поръчай' %>
  </div>
<% end %>

</div>
</div>
</div>

app/views/checkouts/edit.html.erb
<h1>Editing checkout</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkout %> |
<%= link_to 'Back', checkouts_path %>

app/views/checkouts/index.html.erb
<h1>Listing checkouts</h1>

<table>
  <thead>
    <tr>
      <th>Cart</th>
      <th>Name</th>
      <th>Telephone</th>
      <th>Adress</th>
      <th>City</th>
      <th>Email</th>
      <th>Delivery type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @checkouts.each do |checkout| %>
      <tr>
        <td><%= checkout.cart_id %></td>
        <td><%= checkout.name %></td>
        <td><%= checkout.telephone %></td>
        <td><%= checkout.adress %></td>
        <td><%= checkout.city %></td>
        <td><%= checkout.email %></td>
        <td><%= checkout.delivery_type %></td>
        <td><%= link_to 'Show', checkout %></td>
        <td><%= link_to 'Edit', edit_checkout_path(checkout) %></td>
        <td><%= link_to 'Destroy', checkout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkout', new_checkout_path %>

app/views/checkouts/new.html.erb
<div class="row">
<div class="col-xs-12">
    <ul class="nav nav-pills nav-justified thumbnail">
        <li><a href="<%= user_cart_path %>">
            <h4 class="list-group-item-heading">Стъпка 1</h4>
            <p class="list-group-item-text">Преглед на кошница</p>
        </a></li>
        <li class="active"><a href="#">
            <h4 class="list-group-item-heading">Стъпка 2</h4>
            <p class="list-group-item-text">Поръчка</p>
        </a></li>
        <li class="disabled"><a href="#">
            <h4 class="list-group-item-heading">Стъпка 3</h4>
            <p class="list-group-item-text">Преглед на поръчка</p>
        </a></li>
    </ul>
</div>
</div>
<%= render 'form' %>

app/views/checkouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cart:</strong>
  <%= @checkout.cart_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @checkout.name %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @checkout.telephone %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @checkout.adress %>
</p>

<p>
  <strong>City:</strong>
  <%= @checkout.city %>
</p>

<p>
  <strong>Email:</strong>
  <%= @checkout.email %>
</p>

<p>
  <strong>Delivery type:</strong>
  <%= @checkout.delivery_type %>
</p>

<%= link_to 'Edit', edit_checkout_path(@checkout) %> |
<%= link_to 'Back', checkouts_path %>