config/routes.rb
Nobacco::Application.routes.draw do

  devise_for :users
  resources :additional_images
  resources :checkouts
  resources :in_carts
  resources :products
  resources :sub_categories
  resources :categories
  get "carts/index"
  get "home/index"
  get "control_panel" , to: 'home#control_panel' , as: 'control_panel'
  get "contact_us" , to: 'home#contact_us' , as: 'contact'
  get "cart" , to: 'home#cart' , as: 'user_cart'
  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :bulgarian).to_s
  end

  has_many :sub_categories
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html

  def index
    @category = Category.friendly.find(params[:type])
    return is_authorized
    respond_with(@category)
  end

  def show
    if params[:sub]
      @content = SubCategory.friendly.find(params[:sub])
    else
      @content = @category
    end
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= render 'layouts/adminpanel' %>
<div class="col-md-9">
          <h4><%= @category.name.capitalize %></h4>
          <hr>
          <div class="table-responsive">


                <table id="mytable" class="table table-bordred table-striped">

                     <thead>


                     <th>Продукт</th>
                      <th>Под-Категория</th>
                       <th>Количество</th>
                       <th>Цена</th>
                       <th>Промоция</th>
                        <th>Виж</th>
                        <th>Редактирай</th>
                         <th>Изтрий</th>
                     </thead>
      <tbody>
      <% @category.products.each do |product| %>
      <tr>
      <td> <%= product.name.capitalize %></td>
      <td> <%= product.sub_category ? product.sub_category.name : "-" %></td>
      <td> <%= product.in_stock %></td>
      <td> <%= humanized_money(product.price).to_s + 'лв' %></td>
      <td> <%= product.promotion ? humanized_money(product.promotion).to_s + 'лв' : '-' %> </td>
      <td> <%= link_to 'Виж', product %></td>
      <td> <%= link_to 'Редактирай', edit_product_path(product) %> </td>
      <td> <%= link_to 'Изтрий', product, method: :delete, data: { confirm: 'Сигурни ли сте?' } %> </td>
      </tr>
      <% end %>




      </tbody>

  </table>

  <div class="clearfix"></div>

              </div>

          </div>
    </div>
  </div>



        <!-- /.modal-dialog -->
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<style>
.col-item
{
  border: 1px solid #E1E1E1;
  border-radius: 5px;
  background: #FFF;
}
.col-item .photo img
{
  margin: 0 auto;
  width: 100%;
}

.col-item .info
{
  padding: 10px;
  border-radius: 0 0 5px 5px;
  margin-top: 1px;
}

.col-item:hover .info {
  background-color: #F5F5DC;
}
.col-item .price
{
  /*width: 50%;*/
  float: left;
  margin-top: 5px;
}

.col-item .price h5
{
  line-height: 20px;
  margin: 0;
}

.price-text-color
{
  color: #219FD1;
}

.col-item .info .rating
{
  color: #777;
}

.col-item .rating
{
  /*width: 50%;*/
  float: left;
  font-size: 17px;
  text-align: right;
  line-height: 52px;
  margin-bottom: 10px;
  height: 52px;
}

.col-item .separator
{
  border-top: 1px solid #E1E1E1;
}

.clear-left
{
  clear: left;
}

.col-item .separator p
{
  line-height: 20px;
  margin-bottom: 0;
  margin-top: 10px;
  text-align: center;
}

.col-item .separator p i
{
  margin-right: 5px;
}
.col-item .btn-add
{
  width: 50%;
  float: left;
}

.col-item .btn-add
{
  border-right: 1px solid #E1E1E1;
}

.col-item .btn-details
{
  width: 50%;
  float: left;
  padding-left: 10px;
}
.controls
{
  margin-top: 20px;
}
[data-slide="prev"]
{
  margin-right: 10px;
}
#cat-link{
  color:black;
}
</style>
<% if @category.sub_categories.exists? %>
<div class="col-sm-4 col-md-3 sidebar" style="height:100%;padding-bottom:100%;">
  <div class="mini-submenu">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </div>
  <div class="list-group">
    <span href="#" class="list-group-item <%= "active" if request.original_url == category_url(@category) %>">
      <a id ="cat-link" href="<%= category_path(@category) %>"><%= @category.name.capitalize %></a>
    </span>
    <% @category.sub_categories.each do |sub| %>
    <a href="<%= category_path(sub.category , :sub => sub) %>" class="list-group-item <%= "active" if request.original_url == category_url(sub.category , :sub => sub) %>">
      <i class="fa fa-angle-right" style="font-size:90%;"></i> <%= sub.name %>
    </a>
    <% end %>
  </div>
</div>
<% end %>

<% @content.products.each do |product| %>
<div class="col-sm-3" style="padding-bottom:10px;padding:4px;">
<div class="col-item">
<div class="photo">
<img src="<%= product.image.thumb %>" class="img-responsive" alt="a" />
</div>
<div class="info">
<div class="row">
  <div class="price col-md-6">
    <h5>
      <%= product.name %></h5>
      <h5 class="price-text-color">
      <%= humanized_money product.price %>лв</h5>
      </div>
      <div class="rating hidden-sm col-md-6">
      </div>
    </div>
    <div class="separator clear-left">
      <p class="btn-add">
        <i class="fa fa-shopping-cart"></i><a href="<%= new_in_cart_path(:product => product.id) %>" data-remote="true" class="hidden-sm">Добави в количка</a></p>
        <p class="btn-details">
          <i class="fa fa-info-circle"></i><a href="<%= product_path(product) %>" class="hidden-sm">Повече информация</a></p>
        </div>
        <div class="clearfix">
        </div>
      </div>
    </div>
  </div>
<% end %>