config/routes.rb
Nobacco::Application.routes.draw do

  devise_for :users
  resources :additional_images
  resources :checkouts
  resources :in_carts
  resources :products
  resources :sub_categories
  resources :categories
  get "carts/index"
  get "home/index"
  get "control_panel" , to: 'home#control_panel' , as: 'control_panel'
  get "contact_us" , to: 'home#contact_us' , as: 'contact'
  get "cart" , to: 'home#cart' , as: 'user_cart'
  root 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, length: { minimum: 5 }
  validates :category_id , :in_stock ,:price , :description , presence: true
  validates :in_stock , numericality: { only_integer: true , greater_than: 0 }
 


  mount_uploader :image , ImageUploader
  extend FriendlyId
  friendly_id :name, use: :slugged
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :bulgarian).to_s
  end

  belongs_to :category
  belongs_to :sub_category , foreign_key: "subcategory_id"
  has_many :additional_image , :dependent => :destroy
  accepts_nested_attributes_for :additional_image

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html

  def index
    @products = Product.all
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    @category = Category.friendly.find(params[:type])
    4.times{@product.additional_image.build}
    respond_with(@product)
  end

  def edit
    4.times{@product.additional_image.build}
    @category = @product.category
  end

  def create
    @product = Product.new(product_params)
    @product.colors = color(params[:red],params[:blue],params[:black],params[:inox])
    @product.nicotine = get_nicotine(params[:a],params[:b],params[:c],params[:d],params[:e])
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    @product.colors = color(params[:red],params[:blue],params[:black],params[:inox])
    @product.nicotine = get_nicotine(params[:a],params[:b],params[:c],params[:d],params[:e])
    @product.save
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private

    def color(red,blue,black,inox)
      color = ""
      if red
        color += "r"
      end
      if blue
        color += "b"
      end
      if black
        color += "c"
      end
      if inox
        color += "i"
      end
      return color
    end

    def get_nicotine(a,b,c,d,e)
      nicotine = ""
      if a
        nicotine += a.to_s
      end
      if b
        nicotine += b.to_s
      end
      if c
        nicotine += c.to_s
      end
      if d
        nicotine += d.to_s
      end
      if e
        nicotine += e.to_s
      end
      return nicotine.to_s
    end

    def set_product
      @product = Product.friendly.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :promotion, :category_id, :nicotine , :subcategory_id, :colors, :in_stock, :description, :image , additional_image_attributes: [:id,:image,:product_id] )
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def in_stock(stock)
    in_stock = '<i class="fa fa-check"></i>&nbsp; В наличност'.html_safe
    out_of_stock = '<span style="color:#FF3333"><i class="fa fa-times"></i>&nbsp; Няма в наличност</span>'.html_safe
    if stock >= 1
      return in_stock
    else
      return out_of_stock
    end
  end

  def colors(str)
    output = ""

    if str.to_s.length < 1
      return ""
    end
    str.split("").each do |i|
      if i == "r"
        output += '<i class="fa fa-circle" style="color:firebrick;"></i>&nbsp;'
      end
      if i == "b"
        output += '<i class="fa fa-circle" style="color:steelblue;"></i>&nbsp;'
      end
      if i == "c"
        output += '<i class="fa fa-circle" style="color:black;"></i>&nbsp;'
      end
      if i == "i"
        output += '<i class="fa fa-circle" style="color:silver;"></i>&nbsp;'
      end
    end
    return ("Цветове: " + output).html_safe
  end

  def nicotine(str)
    output = "Никотин: "
    if str.to_s.length < 1
      return ""
    end
    str.split("").each do |i|
      if i == 'a'
        output += " 0% "
      end
      if i == 'b'
        output += " ,0.6% "
      end
      if i == 'c'
        output += " ,0.9% "
      end
      if i == 'd'
        output += " ,1.2% "
      end
      if i == 'e'
        output += " ,1.8% "
      end
    end
    return output
  end
end

app/views/products/_form.html.erb
<%= bootstrap_form_for(@product , url: products_path , :multipart => true) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :category_id, :value => @category.id%>
  <div class="field">
    <%= f.label :name, 'Име на продукта' %><br>
    <%= f.text_field :name , hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :price, 'Цена' %><br>
    <%= f.text_field :price , hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :promotion, 'Промоция' %><br>
    <%= f.text_field :promotion , hide_label: true %>
  </div>
  <% if @category.sub_categories.exists? %>
  <div class="field">
    <%= f.label :subcategory_id , 'Под-Категория' %><br>
    <%= f.select :subcategory_id , options_for_select(SubCategory.where(:category_id => @category.id).collect{ |f| [f.name, f.id] }) , hide_label: true %>
  </div>
  <% end %>

  <% if params[:type] == "technosti" %>
  <div class="field">
    <%= f.label :nicotine , 'Никотин:' %><br>
    <label class="checkbox-inline">
      <%= check_box_tag 'a', 'a' %> 0%
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'b', 'b' %> 0.6%
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'c', 'c' %> 0.9%
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'd', 'd' %> 1.2%
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'e', 'e' %> 1.8%
    </label>
  </div>
<br>
   <% end %>
  <div class="field">
    <%= f.label :in_stock , 'В наличност' %><br>
    <%= f.number_field :in_stock , hide_label: true %>
  </div>
  <div class="field">
    <%= tinymce_assets %>
    <%= tinymce %>
    <%= f.label :description , 'Описание' %><br>
    <%= f.text_area :description , :class => "tinymce", :rows => 10, :cols => 10 , hide_label: true %>
  </div>
  <% unless params[:type] == "technosti" || params[:type] == "bijuta" %>
  <div class="field">
    <%= f.label :colors , 'Цветове:' %><br>

    <label class="checkbox-inline">
      <%= check_box_tag 'red', 'red' %> Червен
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'blue', 'blue' %> Син
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'black', 'black' %> Черен
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'inox', 'inox' %> Inox
    </label>
  </div>
  <% end %>
<br>
  <div class="field">
    <%= f.label :image, "Главна Снимка" %><br>
    <%= f.file_field :image , hide_label: true %>
  </div>
  <div class="field">
    <hr>
    <h4>Допълнителни Снимки:</h4>
    <hr>
  </div>

  <% i=0 %>
  <%= f.fields_for :additional_image do |builder| %>
  <p>
    <%= builder.label :image , "Снимка #{i+=1}" %>
    <%= builder.file_field :image , hide_label: true %>
  </p>
  <% end %>
  <div class="actions">
    <%= f.submit "Създай Продукт" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%= bootstrap_form_for(@product , url: product_path(@product) , :multipart => true) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :category_id, :value => @category.id%>
  <div class="field">
    <%= f.label :name, 'Име на продукта' %><br>
    <%= f.text_field :name , hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :price, 'Цена' %><br>
    <%= f.text_field :price , hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :promotion, 'Промоция' %><br>
    <%= f.text_field :promotion , hide_label: true %>
  </div>
  <% if @category.sub_categories.exists? %>
  <div class="field">
    <%= f.label :subcategory_id , 'Под-Категория' %><br>
    <%= f.select :subcategory_id , options_for_select(SubCategory.where(:category_id => @category.id).collect{ |f| [f.name, f.id] }) , hide_label: true %>
  </div>
  <% end %>

  <% if params[:type] == "technosti" %>
  <div class="field">
    <%= f.label :nicotine , 'Никотин:' %><br>
    <label class="checkbox-inline">
      <%= check_box_tag 'a', 'a' %> 0%
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'b', 'b' %> 0.6%
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'c', 'c' %> 0.9%
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'd', 'd' %> 1.2%
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'e', 'e' %> 1.8%
    </label>
  </div>
<br>
   <% end %>
  <div class="field">
    <%= f.label :in_stock , 'В наличност' %><br>
    <%= f.number_field :in_stock , hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :description , 'Описание' %><br>
    <%= f.text_area :description , hide_label: true %>
  </div>
  <% unless params[:type] == "technosti" || params[:type] == "bijuta" %>
  <div class="field">
    <%= f.label :colors , 'Цветове:' %><br>

    <label class="checkbox-inline">
      <%= check_box_tag 'red', 'red' %> Червен
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'blue', 'blue' %> Син
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'black', 'black' %> Черен
    </label>
    <label class="checkbox-inline">
      <%= check_box_tag 'inox', 'inox' %> Inox
    </label>
  </div>
  <% end %>
<br>
  <div class="field">
    <%= f.label :image, "Главна Снимка" %><br>
    <%= f.file_field :image , hide_label: true %>
  </div>
  <div class="field">
    <hr>
    <h4>Допълнителни Снимки:</h4>
    <hr>
  </div>

  <% i=0 %>
  <%= f.fields_for :additional_image do |builder| %>
  <p>
    <%= builder.label :image , "Снимка #{i+=1}" %>
    <%= builder.file_field :image , hide_label: true %>
  </p>
  <% end %>
  <div class="actions">
    <%= f.submit "Създай Продукт" %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Promotion</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th>Colors</th>
      <th>In stock</th>
      <th>Description</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.promotion %></td>
        <td><%= product.category_id %></td>
        <td><%= product.subcategory_id %></td>
        <td><%= product.colors %></td>
        <td><%= product.in_stock %></td>
        <td><%= product.description %></td>
        <td><%= product.image %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<%= render 'layouts/adminpanel' %>
<div class="col-md-5">
<h1>Добави <%=Category.friendly.find(params[:type]).name %></h1>
<hr>
<%= render 'form' %>
</div>

app/views/products/show.html.erb
<style>
/*********************************************
Call Bootstrap
*********************************************/

@import url("bootstrap/bootstrap.min.css");
@import url("bootstrap-override.css");
@import url("//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css");

/*********************************************
Theme Elements
*********************************************/

.gold{
  color: #FFBF00;
}

/*********************************************
PRODUCTS
*********************************************/

.product{
  border: 1px solid #dddddd;
  height: 321px;
}

.product>img{
  max-width: 230px;
}

.product-rating{
  font-size: 20px;
  margin-bottom: 25px;
}

.product-title{
  font-size: 24px;
}

.product-desc{
  font-size: 14px;
}

.product-price{
  font-size: 22px;
}

.product-stock{
  color: #74DF00;
  font-size: 20px;
  margin-top: 10px;
}

.product-info{
  margin-top: 50px;
}

/*********************************************
VIEW
*********************************************/

.content-wrapper {
  max-width: 1140px;
  margin: 0 auto;
  margin-top: 25px;
  margin-bottom: 10px;
  border: 0px;
  border-radius: 0px;
}

.container-fluid{
  margin: 0 auto;
}

.view-wrapper {
  float: right;
  max-width: 70%;
  margin-top: 25px;
}

.container {
  padding-left: 0px;
  padding-right: 0px;
  max-width: 100%;
}

/*********************************************
ITEM
*********************************************/

.service1-items {
  padding: 0px 0 0px 0;
  float: left;
  position: relative;
  overflow: hidden;
  max-width: 100%;
  height: 321px;
  width: 130px;
}

.service1-item {
  height: 107px;
  width: 120px;
  display: block;
  float: left;
  position: relative;
  padding-right: 20px;
  border-right: 1px solid #DDD;
  border-top: 1px solid #DDD;
  border-bottom: 1px solid #DDD;
}

.service1-item > img {
  max-height: 110px;
  max-width: 110px;
  opacity: 0.6;
  transition: all .2s ease-in;
  -o-transition: all .2s ease-in;
  -moz-transition: all .2s ease-in;
  -webkit-transition: all .2s ease-in;
}

.service1-item > img:hover {
  cursor: pointer;
  opacity: 1;
}

.service-image-left {
  padding-right: 50px;
}

.service-image-right {
  padding-left: 50px;
}

.service-image-left > center > img,.service-image-right > center > img{
  max-height: 155px;
}
</style>
<script>
      $(document).ready(function(){
        $('#etalage').etalage({
          thumb_image_width: 300,
          thumb_image_height: 300,
          source_image_width: 900,
          source_image_height: 1200
        });
      });
</script>

<ol class="breadcrumb" style="border-bottom:1px solid #E4E4E4;margin-top:-1.5%;">
  <li><a href="<%= category_path(@product.category) %>"><%= @product.category.name.capitalize %></a></li>
  <%= "<li><a href=\"#{category_path(@product.category , :sub => @product.sub_category)}\">#{@product.sub_category.name}</a></li>".html_safe if @product.sub_category %>
  <li class="active"><%= @product.name %></li>
</ol>
<% if flash[:notice] %>
<div class="alert alert-success" role="alert"><%= flash[:notice].to_s %></div>
<% end %>
<div class="content-wrapper">
  <div class="item-container">
      <div class="col-md-4">
        <ul id="etalage">
      <li>
        <img class="etalage_thumb_image" src="<%= @product.image.thumb %>">
        <img class="etalage_source_image" src="<%= @product.image_url %>">
      </li>
      <% @product.additional_image.each do |add| %>
      <li>
        <img class="etalage_thumb_image" src="<%= add.image.thumb %>">
        <img class="etalage_source_image" src="<%= add.image_url %>">
      </li>
      <% end %>
    </ul>
      </div>

      <div class="col-md-7">
        <div class="product-title"><h2><%= @product.name.capitalize %></h2></div>
        <div class="product-desc"><%= sanitize(@product.description,:tags=>[]).split(".").first.html_safe  %></div>
        <hr>
        <div class="product-rating"><%= colors(@product.colors) %></div>
        <div class="product-rating"><%= nicotine(@product.nicotine) %></div>
        <hr>
        <div class="product-price"><%= humanized_money @product.price %>лв</div>
        <div class="product-stock"><%= in_stock(@product.in_stock) %></div>
        <hr>
        <div class="btn-group cart">
          <a href="<%= new_in_cart_path(:product => @product.id) %>" data-remote="true" type="button" class="btn btn-success">
            <i class="fa fa-cart-plus"></i> &nbsp; Добави в кошница
          </a>
        </div>
        </div>

    </div>
  </div>
  <div class="container-fluid">
    <div class="col-md-12 product-info">
      <ul id="myTab" class="nav nav-tabs nav_tabs">

        <li class="active"><a href="#service-one" data-toggle="tab">Описание</a></li>


      </ul>
      <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade in active" id="service-one">

          <section class="container product-info">
            <%= @product.description.html_safe %>
          </section>

        </div>
        <div class="tab-pane fade" id="service-two">

          <section class="container">

          </section>

        </div>
        <div class="tab-pane fade" id="service-three">

        </div>
      </div>
      <hr>
    </div>
  </div>