config/routes.rb
Nobacco::Application.routes.draw do

  devise_for :users
  resources :additional_images
  resources :checkouts
  resources :in_carts
  resources :products
  resources :sub_categories
  resources :categories
  get "carts/index"
  get "home/index"
  get "control_panel" , to: 'home#control_panel' , as: 'control_panel'
  get "contact_us" , to: 'home#contact_us' , as: 'contact'
  get "cart" , to: 'home#cart' , as: 'user_cart'
  root 'home#index'

end

app/views/layouts/_adminpanel.html.erb
<div class="col-sm-3 col-md-3">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            Добави Продукт</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                              <% Category.all.each do |cat| %>
                                <tr>
                                    <td>
                                    </span><a href="<%= new_product_path(:type => cat.slug) %>">Добави <%= cat.name %></a>
                                    </td>
                                </tr>
                                <% end %>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Стока и поръчки</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                              <% Category.all.each do |cat| %>
                                <tr>
                                    <td>
                                        <a href="<%= categories_path(:type => cat.slug) %>"><%= cat.name %></a>
                                    </td>
                                </tr>
                                <% end %>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

app/views/layouts/_footer.html.erb
<style>
.cuadro_intro_hover{
        padding: 0px;
    position: relative;
    overflow: hidden;
    height: 200px;
  }
  .cuadro_intro_hover:hover .caption{
    opacity: 1;
    transform: translateY(-150px);
    -webkit-transform:translateY(-150px);
    -moz-transform:translateY(-150px);
    -ms-transform:translateY(-150px);
    -o-transform:translateY(-150px);
  }
  .cuadro_intro_hover img{
    z-index: 4;
  }
  .cuadro_intro_hover .caption{
    position: absolute;
    top:150px;
    -webkit-transition:all 0.3s ease-in-out;
    -moz-transition:all 0.3s ease-in-out;
    -o-transition:all 0.3s ease-in-out;
    -ms-transition:all 0.3s ease-in-out;
    transition:all 0.3s ease-in-out;
    width: 100%;
  }
  .cuadro_intro_hover .blur{
    background-color: rgba(0,0,0,0.7);
    height: 300px;
    z-index: 5;
    position: absolute;
    width: 100%;
  }
  .cuadro_intro_hover .caption-text{
    z-index: 10;
    color: #fff;
    position: absolute;
    height: 300px;
    text-align: center;
    top:-20px;
    width: 100%;
  }
</style>
<hr>
        <footer>
            <div class="row">
                <div class="col-lg-11">


      <div class="col-lg-3">
            <div class="cuadro_intro_hover " style="background-color:#cccccc;">
            <p style="text-align:center; margin-top:20px;">
              <img src="http://placehold.it/500x330" class="img-responsive" alt="">
            </p>
            <div class="caption">
              <div class="blur"></div>
              <div class="caption-text">
                <h3 style="border-top:2px solid white; border-bottom:2px solid white; padding:10px;">THIS IS H3</h3>
                <p>Loren ipsum dolor si amet ipsum dolor si amet ipsum dolor...</p>
                <a class=" btn btn-default" href="#"><span class="glyphicon glyphicon-plus"> INFO</span></a>
              </div>
            </div>
          </div>

      </div>
       <div class="col-lg-3">
            <div class="cuadro_intro_hover " style="background-color:#cccccc;">
            <p style="text-align:center; margin-top:20px;">
              <img src="http://placehold.it/500x330" class="img-responsive" alt="">
            </p>
            <div class="caption">
              <div class="blur"></div>
              <div class="caption-text">
                <h3 style="border-top:2px solid white; border-bottom:2px solid white; padding:10px;">THIS IS H3</h3>
                <p>Loren ipsum dolor si amet ipsum dolor si amet ipsum dolor...</p>
                <a class=" btn btn-default" href="#"><span class="glyphicon glyphicon-plus"> INFO</span></a>
              </div>
            </div>
          </div>

      </div>


            <div class="col-lg-3 col-md-6">
      <h3>Категории:</h3>
                <ul>
        <% Category.all.each do |cat| %>
        <li><%= link_to cat.name.capitalize , cat %></li>
        <% end %>
        </ul>
            </div>

            <div class="col-lg-3 col-md-6">
                <h3>Контакти:</h3>
        <p>Имате въпрос? Свържете се с нас!</p>
        <p><a href="" title="Contact me!"><i class="fa fa-envelope"></i> Контакти</a></p>
            <h3>Follow:</h3>


<a href="" id="gh" target="_blank" title="Twitter"><span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-twitter fa-stack-1x"></i>
</span>
Twitter</a>
<a href=""  target="_blank" title="GitHub"><span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-github fa-stack-1x"></i>
</span>
GitHub</a>






      </div>
      <br/>
            <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/hu_HU/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

<a href="https://twitter.com/share" class="twitter-share-button" data-url="">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<div class="g-plusone" data-annotation="inline" data-width="300" data-href=""></div>

<!-- Helyezd el ezt a címkét az utolsó +1 gomb címke mögé. -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
      <br/>

        </footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation" style="margin-bottom:2%;">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-brand-centered">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-brand-centered">
      <ul class="nav navbar-nav">
        <% Category.all.each do |category| %>
        <li class="<%= "active" if request.original_url == category_url(category) %>"><%=link_to category.name , category %></li>

        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Контакти' , contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nobacco</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= cart %>
<div class="container-fluid" style="padding-left:7%;padding-right:7%;padding-top:5px;">
  <% if current_user %>
  <p class="pull-left"><%= link_to 'Контролен Панел' , control_panel_path %>
  <p>&nbsp;&nbsp; | &nbsp;&nbsp;<%= link_to('Изход', destroy_user_session_path, :method => :delete) %></p>
  </p>
  <% end %>
<p class="pull-right">
<a href="<%= user_cart_path %>"><i class="fa fa-shopping-cart"></i>&nbsp;Кошница (<%= Cart.find(cookies[:cart]).in_carts.size %>)</a>

</p>
<a href="<%= root_path %>"><img src="/logo2.png" class="img-responsive" style="padding-bottom:8px;padding-top:5px;max-width:350px;"></a>
<div id="wrapper-content" class="container-fluid" style="background-color:#F6F6E5;padding:0;padding-bottom:30px;min-height:700px;">
<%= render 'layouts/header' %>
<%= yield %>

</div>
<%= render 'layouts/footer' %>

</div>
</body>
</html>